services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: op-succinct
      POSTGRES_DB: op-succinct
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "op-succinct", "-p", "5432" ]
      interval: 30s
      timeout: 15s
      retries: 10
    ports:
      - "5432:5432"

  alloy:
    build:
      context: .
      dockerfile: Dockerfile.alloy
    volumes:
      - ./config.alloy:/etc/alloy/test.alloy
      - alloy-data:/var/lib/alloy/data
    ports:
      - "12345:12345" # UI/API port
      - "4317:4317" # OTLP gRPC
      - "4318:4318" # OTLP HTTP
    command: >
      run  --server.http.listen-addr=0.0.0.0:12345  --storage.path=/var/lib/alloy/data  /etc/alloy/test.alloy
    healthcheck:
      test: [ "CMD-SHELL", "nc -z localhost 12345" ]
      interval: 10s
      timeout: 5s
      retries: 5
    network_mode: host
    deploy:
      resources:
        reservations:
          cpus: '1'

  op-succinct:
    build:
      context: .
      dockerfile: ./validity/Dockerfile
    network_mode: host
    env_file:
      - ${ENV_FILE:-.env}
    environment:
      - DATABASE_URL=postgres://op-succinct@localhost:5432/op-succinct
    depends_on:
      - postgres
      - alloy
    restart: unless-stopped

volumes:
  postgres-data:
  alloy-data:
