services:
  prometheus:
    image: prom/prometheus:katest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - proposer_network

  # OP Succinct Server
  op-succinct-server:
    build:
      context: .
      dockerfile: ./proposer/succinct/Dockerfile
    env_file:
      - ${ENV_FILE:-.env}
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - proposer_network

  # OP Succinct Proposer
  op-succinct-proposer:
    build:
      context: .
      dockerfile: ./proposer/op/Dockerfile.op_proposer
    env_file:
      - ${ENV_FILE:-.env}
    restart: unless-stopped
    depends_on:
      - op-succinct-server
    volumes:
      - ./db:/usr/local/bin/dbdata
    networks:
      - proposer_network
