services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: op-succinct
      POSTGRES_DB: op-succinct
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "op-succinct", "-p", "5432" ]
      interval: 30s
      timeout: 15s
      retries: 10
    ports:
      - "5432:5432"

  op-succinct:
    build:
      context: .
      dockerfile: ./validity/Dockerfile
    network_mode: host
    env_file:
      - ${ENV_FILE:-.env}
    environment:
      - DATABASE_URL=postgres://op-succinct@localhost:5432/op-succinct
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres-data:
