services:
  # OP Succinct Server
  op-succinct-server:
    build:
      context: .
      dockerfile: ./proposer/succinct/Dockerfile
    env_file:
      - ${ENV_FILE:-.env.phala}
    restart: unless-stopped
    ports:
      - "3000:3000"
      - "9090:9090"
    networks:
      - monitoring

  # OP Succinct Proposer
  op-succinct-proposer:
    build:
      context: .
      dockerfile: ./proposer/op/Dockerfile.op_proposer
    env_file:
      - ${ENV_FILE:-.env.phala}
    restart: unless-stopped
    depends_on:
      - op-succinct-server
    ports:
      - "7300:7300"
    volumes:
      - ./db:/usr/local/bin/dbdata
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge
