networks:
  monitoring:
    driver: bridge

services:
  op-succinct-lite-proposer:
    build:
      context: ..
      dockerfile: fault-proof/Dockerfile.proposer
    container_name: op-succinct-lite-proposer
    restart: unless-stopped
    env_file:
      - .env.proposer
    command: ["proposer"]
    ports:
      - "9090:9090"  # Expose metrics port (adjust if needed)
    networks:
      - monitoring

  op-succinct-lite-challenger:
    build:
      context: ..
      dockerfile: fault-proof/Dockerfile.challenger
    container_name: op-succinct-lite-challenger
    restart: unless-stopped
    env_file:
      - .env.challenger
    command: ["challenger"]
    ports:
      - "9091:9091"  # Expose metrics port (adjust if needed)
    networks:
      - monitoring

  alloy:
    build:
      context: .
      dockerfile: Dockerfile.alloy
    volumes:
      - ./config.alloy:/etc/alloy/test.alloy
      - alloy-data:/var/lib/alloy/data
    ports:
      - "12345:12345"  # UI/API port
      - "4317:4317"    # OTLP gRPC
      - "4318:4318"    # OTLP HTTP
    networks:
      - monitoring
    depends_on:
      - op-succinct-lite-proposer
      - op-succinct-lite-challenger
    command: >
      run 
      --server.http.listen-addr=0.0.0.0:12345 
      --storage.path=/var/lib/alloy/data 
      /etc/alloy/test.alloy
    healthcheck:
      # test:
      #   [
      #     "CMD-SHELL",
      #     "wget --spider -q http://0.0.0.0:12345/-/healthy || (echo 'Health check failed' && exit 1)",
      #   ]
      test: ["CMD-SHELL", "nc -z localhost 12345"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  alloy-data:
