name: SQLx Query Check

on:
  pull_request:
    paths:
      - '**/*.rs'
      - '**/*.sql'
      - 'sqlx-data.json'
      - 'Cargo.toml'
      - 'Cargo.lock'
  workflow_dispatch:

jobs:
  sqlx-check:
    name: Verify SQLx queries
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup environment
        uses: ./.github/actions/setup
      
      - name: Install SQLx CLI
        run: cargo install sqlx-cli --no-default-features --features native-tls,postgres
      
      - name: Verify SQLx query files
        run: cd validity && cargo sqlx prepare --check